-- crear la BD

CREATE DATABASE trailerflix;

-- ----- -------- Crear las tablas:

-- Tabla Categorías
CREATE TABLE Categorias (
    categoriaID INT AUTO_INCREMENT PRIMARY KEY,
    categoria VARCHAR(50) NOT NULL
);

-- Tabla Géneros
CREATE TABLE Generos (
    generoID INT AUTO_INCREMENT PRIMARY KEY,
    genero VARCHAR(50) NOT NULL
);

-- Tabla Tags
CREATE TABLE Tags (
    tagID INT AUTO_INCREMENT PRIMARY KEY,
    tag VARCHAR(50) NOT NULL
);

-- Tabla Actores
CREATE TABLE Actores (
    actorID INT AUTO_INCREMENT PRIMARY KEY,
    nombreCompleto VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS actores; -- elimino actores anterior
 -- creo actores nueva
CREATE TABLE actores (
  actorID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombreCompleto VARCHAR(255)
);

-- Tabla Contenidos
CREATE TABLE Contenidos (
    contenidoID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    poster VARCHAR(255),
    titulo VARCHAR(255) NOT NULL,
    categoriaID INT,
    generoID INT,
    resumen TEXT,
    temporadas INT,
    duracion VARCHAR(50),
    trailer VARCHAR(255),
    FOREIGN KEY (categoriaID) REFERENCES Categorias(categoriaID),
    FOREIGN KEY (generoID) REFERENCES Generos(generoID)
);


-- Tabla intermedia: Contenido-Actores
CREATE TABLE contenido_actores (
  contenidoID INT NOT NULL,
  actorID INT NOT NULL,
  PRIMARY KEY (contenidoID, actorID),
  FOREIGN KEY (contenidoID) REFERENCES contenidos(contenidoID),
  FOREIGN KEY (actorID) REFERENCES actores(actorID)
);


-- Tabla intermedia: Contenido-Tags
CREATE TABLE Contenido_Tags (
    contenidoID INT NOT NULL,
    tagID INT NOT NULL,
    PRIMARY KEY (contenidoID, tagID),
    FOREIGN KEY (contenidoID) REFERENCES Contenidos(contenidoID),
    FOREIGN KEY (tagID) REFERENCES Tags(tagID)
);




-- --------- cargar datos en las tablas

-- Tabla Categorías
INSERT INTO Categorias (categoria) VALUES
('Película'),
('Serie');


-- Tabla Géneros
INSERT INTO Generos (genero) VALUES
('Acción'),
('Aventura'),
('Ciencia Ficción'),
('Comedia'),
('Drama'),
('Familia'),
('Fantasía'),
('Suceso Real'),
('Suspenso'),
('Terror');


-- Tabla Tags
INSERT INTO Tags (tag) VALUES
('acción'),
('animación'),
('aventura'),
('ciencia ficción'),
('comedia'),
('crimen'),
('drama'),
('familia'),
('fantasía'),
('ficción'),
('futurista'),
('historia'),
('intriga'),
('misterio'),
('musical'),
('música'),
('romance'),
('sci-fi'),
('suceso real'),
('sucesos'),
('suspenso'),
('tecnología'),
('terror'),
('western');



-- tabla actores

INSERT INTO `actores` (`actorID`, `nombreCompleto`) VALUES -- (original dice: INSERT INTO `Actores` (`id`, `nombreCompleto`) VALUES)
(1, "Pedro Pascal"),
(2, "Carl Weathers"),
(3, "Chris Bartlett"),
(4, "Rio Hackford"),
(5, "Giancarlo Esposito"),
(6, "Tom Hopper"),
(7, "David Castañeda"),
(8, "Emmy Raver-Lampman"),
(9, "Robert Sheehan"),
(10, "Aidan Gallagher"),
(11, "Elliot Page"),
(12, "Anya Taylor-Joy"),
(13, "Thomas Brodie-Sangster"),
(14, "Harry Melling"),
(15, "Moses Ingram"),
(16, "Janina Elkin"),
(17, "Lili Reinhart"),
(18, "Casey Cott"),
(19, "Camila Mendes"),
(20, "Marisol Nichols"),
(21, "Madelaine Petsch"),
(22, "Mädchen Amick"),
(23, "Claire Fox"),
(24, "Olivia Colman"),
(25, "Misty Rosas"),
(26, "Matt Smith"),
(27, "Vanesa Kirby"),
(28, "Helena Bonham Carter"),
(29, "Millie Bobby Brown"),
(30, "Henry Cavill"),
(31, "Sam Claflin"),
(32, "Louis Partridge"),
(33, "Adeel Akhtar"),
(34, "Robert De Niro"),
(35, "Zazie Beetz"),
(36, "Frances Conroy"),
(37, "Shea Whigham"),
(38, "Robert Downey Jr."),
(39, "Chris Evans"),
(40, "Mark Ruffalo"),
(41, "Chris Hemsworth"),
(42, "Jeremy Renner"),
(43, "Emilia Clarke"),
(44, "Lena Headey"),
(45, "Sophie Turner"),
(46, "Kit Harington"),
(47, "Peter Dinklage"),
(48, "Nikolaj Coster-Waldau"),
(49, "Grant Gustin"),
(50, "Carlos Valdes"),
(51, "Danielle Panabaker"),
(52, "Candice Patton"),
(53, "Jesse L. Martin"),
(54, "Tom Cavanagh"),
(55, "Jim Parsons"),
(56, "Johnny Galecki"),
(57, "Kaley Cuoco"),
(58, "Simon Helberg"),
(59, "Kunal Nayyar"),
(60, "Melissa Rauch"),
(61, "Mayim Bialik"),
(62, "Jennifer Aniston"),
(63, "Courteney Cox"),
(64, "Lisa Kudrow"),
(65, "David Schwimmer"),
(66, "Matthew Perry"),
(67, "Matt LeBlanc"),
(68, "Amybeth McNulty"),
(69, "Geraldine James"),
(70, "R. H. Thomson"),
(71, "Corrine Koslo"),
(72, "Dalila Bela"),
(73, "Lucas Jade Zumann"),
(74, "Gillian Anderson"),
(75, "David Duchovny"),
(76, "Mitch Pileggi"),
(77, "Robert Patrick"),
(78, "Tom Braidwood"),
(79, "Bruce Harwood"),
(80, "Jared Harris"),
(81, "Stellan Skarsgård"),
(82, "Paul Ritter"),
(83, "Jessie Buckley"),
(84, "Adam Nagaitis"),
(85, "Evan Rachel Wood"),
(86, "Thandiwe Newton"),
(87, "Jeffrey Wright"),
(88, "Tessa Thompson"),
(89, "Luke Hemsworth"),
(90, "Rodrigo Santoro"),
(91, "Simon Quarterman"),
(92, "Clifton Collins Jr."),
(93, "Anthony Hopkins"),
(94, "Ingrid Bolsø Berdal"),
(95, "Angela Sarafyan"),
(96, "Shannon Woodward"),
(97, "Talulah Riley"),
(98, "Louis Herthum"),
(99, "Ben Barnes"),
(100, "Leonardo Nam"),
(101, "Vincent Cassel"),
(102, "Izabella Alvarez"),
(103, "Jeff Daniel Phillips"),
(104, "Lee Pace"),
(105, "Scoot McNairy"),
(106, "Mackenzie Davis"),
(107, "Toby Huss"),
(108, "Alana Cavanaugh"),
(109, "Colin Farrell"),
(110, "Common"),
(111, "Geena Davis"),
(112, "Ioan Gruffudd"),
(113, "Margot Robbie"),
(114, "Ewan McGregor"),
(115, "Mary Elizabeth Winstead"),
(116, "Jurnee Smollett"),
(117, "Rosie Perez"),
(118, "Chris Messina"),
(119, "Stacy Martin"),
(120, "Rhona Mitra"),
(121, "Theo James"),
(122, "Peter Ferdinando"),
(123, "Lia Williams"),
(124, "Miranda Cosgrove"),
(125, "Kate Walsh"),
(126, "Omar Epps"),
(127, "Angus Macfadyen"),
(128, "Jorja Fox"),
(129, "Enver Gjokaj"),
(130, "Bill Skarsgård"),
(131, "Bill Hader"),
(132, "James McAvoy"),
(133, "Isaiah Mustafa"),
(134, "Jay Ryan"),
(135, "Chadwick Boseman"),
(136, "Michael B. Jordan"),
(137, "Lupita Nyong\'o"),
(138, "Danai Gurira"),
(139, "Martin Freeman"),
(140, "Daniel Kaluuya"),
(141, "Christian Bale"),
(142, "Caitriona Balfe"),
(143, "Noah Jupe"),
(144, "Génesis Rodríguez"),
(145, "Vincent Piazza"),
(146, "Benjamin Sokolow"),
(147, "Emily Bayiokos"),
(148, "Amy Manson"),
(149, "Luke Allen-Gale"),
(150, "Nina Bergman"),
(151, "Dominic Mafham"),
(152, "James Weber Brown"),
(153, "Lorina Kamburova"),
(154, "Marion Cotillard"),
(155, "Jude Law"),
(156, "Kate Winslet"),
(157, "Jennifer Ehle"),
(158, "Gwyneth Paltrow"),
(159, "Scarlett Johansson"),
(160, "Florence Pugh"),
(161, "O.T. Fagbenle"),
(162, "Rachel Weisz"),
(163, "Matt Damon"),
(164, "Jessica Chastain"),
(165, "Kristen Wiig"),
(166, "Jeff Daniels"),
(167, "Michael Peña"),
(168, "Sean Bean"),
(169, "Kate Mara"),
(170, "Alicia Vikander"),
(171, "Domhnall Gleeson"),
(172, "Oscar Isaac"),
(173, "Sonoya Mizuno"),
(174, "Corey Johnson"),
(175, "Claire Selby"),
(176, "Gana Bayarsaikhan"),
(177, "Bryce Dallas Howard"),
(178, "Chris Pratt"),
(179, "Irrfan Khan"),
(180, "Vincent D\'Onofrio"),
(181, "Omar Sy"),
(182, "Nick Robinson"),
(183, "Judy Greer"),
(184, "Will Smith"),
(185, "Alice Braga"),
(186, "Charlie Tahan"),
(187, "Dash Mihok"),
(188, "Salli Richardson-Whitfield"),
(189, "Willow Smith"),
(190, "Emma Thompson"),
(191, "Ryan Gosling"),
(192, "Claire Foy"),
(193, "Jason Clarke"),
(194, "Kyle Chandler"),
(195, "Corey Stoll"),
(196, "Patrick Fugit"),
(197, "John Boyega"),
(198, "Scott Eastwood"),
(199, "Cailee Spaeny"),
(200, "Jing Tian"),
(201, "Rinko Kikuchi"),
(202, "Burn Gorman"),
(203, "Ahston Kutcher"),
(204, "Dermot Mulroney"),
(205, "Josh Gad"),
(206, "Lukas Haas"),
(207, "Matthew Modine"),
(208, "J.K. Simmons"),
(209, "Lesley Ann Warren"),
(210, "Noah Wyle"),
(211, "Anthony Michael"),
(212, "Joey Slotnick"),
(213, "J.G. Hertzler"),
(214, "Wayne Pére"),
(215, "Sheila Shaw"),
(216, "Gemma Zamprogna"),
(217, "John DiMaggio"),
(218, "Jesse Eisenberg"),
(219, "Andrew Garfield"),
(220, "Justin Timberlake"),
(221, "Armie Hammer"),
(222, "Max Minghella"),
(223, "Rooney Mara"),
(224, "Brenda Song"),
(225, "Rashida Jones"),
(226, "John Gertz"),
(227, "Ryan Phillippe"),
(228, "Rachael Leigh Cook"),
(229, "Tim Robbins"),
(230, "Claire Forlani"),
(231, "Richard Rountree"),
(232, "Tygh Runyan"),
(233, "Ned Bellamy"),
(234, "Tyler Labine"),
(235, "Anna Kendrick"),
(236, "Daniel Dae Kim"),
(237, "Shamier Anderson"),
(238, "Toni Collette"),
(239, "Ben Affleck"),
(240, "Gal Gadot"),
(241, "Jason Momoa"),
(242, "Ezra Miller"),
(243, "Ray Fisher"),
(244, "Amy Adams"),
(245, "Jeremy Irons"),
(246, "Connie Nielsen"),
(247, "Charlie Sheen"),
(248, "Jon Cryer"),
(249, "Angus T. Jones"),
(250, "Conchata Ferrel"),
(251, "Holland Taylor"),
(252, "Marin Hinkle"),
(253, "Jennifer Bini Taylor"),
(254, "Melanie Lynskey"),
(255, "Ashton Kutcher"),
(256, "Amber Tamblyn"),
(257, "Úrsula Corberó"),
(258, "Álvaro Morte"),
(259, "Itziar Ituño"),
(260, "Pedro Alonso"),
(261, "Alba Flores"),
(262, "Miguel Herrán"),
(263, "Jaime Lorente"),
(264, "Esther Acebo"),
(265, "Enrique Arce"),
(266, "Winona Ryder"),
(267, "David Harbour"),
(268, "Finn Wolfhard"),
(269, "Gaten Matarazzo"),
(270, "Caleb McLaughlin"),
(271, "Natalia Dyer"),
(272, "Charlie"),
(273, "Heaton"),
(274, "Joe Keery"),
(275, "Sandra Bullock"),
(276, "George Clooney"),
(277, "Orto Ignatiussen"),
(278, "Phaldut Sharma"),
(279, "Amy Warren"),
(280, "Basher Savage"),
(281, "Adam Cozens"),
(282, "Jaeden Martell"),
(283, "Jeremy Ray"),
(284, "Sophia Lillis"),
(285, "Chosen Jacobs"),
(286, "Jack Dylan"),
(287, "Wyatt Oleff"),
(288, "Nicholas Hamilton"),
(289, "Tom Hanks"),
(290, "Bill Paxton"),
(291, "Kevin Bacon"),
(292, "Gary Sinise"),
(293, "Kathleen Quinlan"),
(294, "Roger Corman"),
(295, "Chris Ellis"),
(296, "Xander Berkeley"),
(297, "Liev Schreiber"),
(298, "Julia Stiles"),
(299, "Seamus Davey-Fitzpatrick"),
(300, "David Thewils"),
(301, "Pete Postlethwaite"),
(302, "Mia Farrow"),
(303, "Predrag Bjelac"),
(304, "Carlo Sabatini"),
(305, "Amy Huck"),
(306, "Ellen Burstyn"),
(307, "Linda Blair"),
(308, "Max vox Sydow"),
(309, "Lee J. Cobb"),
(310, "Kitty Winn"),
(311, "Jack MacGowran"),
(312, "Jason Miller"),
(313, "William O\'Malley"),
(314, "Barton Heyman"),
(315, "Rainn Wilson"),
(316, "Steve Carell"),
(317, "Jenna Fischer"),
(318, "John Krasinski"),
(319, "B.J. Novak"),
(320, "Kate Flannery"),
(321, "Brian Baumgartner"),
(322, "Leslie David Baker"),
(323, "Mindy Kaling"),
(324, "Angela Kinsey"),
(325, "Freddie Highmore"),
(326, "Antonia Thomas"),
(327, "Hill Harper"),
(328, "Richard Schiff"),
(329, "Christina Chang"),
(330, "Paige Spara"),
(331, "Fiona Gubelmann"),
(332, "Will Yun Lee"),
(333, "Nicholas Gonzalez"),
(334, "Eddie Redmayne"),
(335, "Felicity Jones"),
(336, "Charlie Cox"),
(337, "Simon McBurney"),
(338, "David Thewlis"),
(339, "Maxine Peake"),
(340, "Harry Lloyd"),
(341, "Tom Prior"),
(342, "Benedict Cumberbatch"),
(343, "Keira Knightley"),
(344, "Matthew Goode"),
(345, "Rory Kinnear"),
(346, "Allen Leech"),
(347, "Matthew Beard"),
(348, "Charles Dance"),
(349, "Mark Strong"),
(350, "James Northcote"),
(351, "Taraji P. Henson"),
(352, "Octavia Spencer"),
(353, "Janelle Monáe"),
(354, "Kevin Costner"),
(355, "Kirsten Dunst"),
(356, "Mahershala Ali"),
(357, "Glen Powell"),
(358, "Ariana Neal"),
(359, "Russell Crowe"),
(360, "Jennifer Connelly"),
(361, "Ed Harris"),
(362, "Paul Bettany"),
(363, "Christopher Plummer"),
(364, "Josh Lucas"),
(365, "Adam Goldberg"),
(366, "Anthony Rapp"),
(367, "Judd Hirsch"),
(368, "Jennifer Lawrence"),
(369, "Michael Sheen"),
(370, "Laurence Fishburne"),
(371, "Andy García"),
(372, "Aurora Perrineau"),
(373, "Kristin Brock"),
(374, "Julee Cerda"),
(375, "Fred Melamed"),
(376, "Anne Hathaway"),
(377, "Patrick Wilson"),
(378, "Andre Braugher"),
(379, "Dianne Wiest"),
(380, "David Morse"),
(381, "William B. Davis"),
(382, "Ryan Robbins"),
(383, "Clea DuVall"),
(384, "Don Thompson"),
(385, "Bryan Cranston"),
(386, "Alan Arkin"),
(387, "Jogn Goodman"),
(388, "Victor Garber"),
(389, "Tate Donovan"),
(390, "Rory Cochrane"),
(391, "Kerry Bishé"),
(392, "Noomi Rapace"),
(393, "Michael Fassbender"),
(394, "Charlize Theron"),
(395, "Logan Marshall-Green"),
(396, "Guy Pearce"),
(397, "Idris Elba"),
(398, "Sean Harris"),
(399, "Rafe Spall"),
(400, "Kate Dickie"),
(401, "Emut Elliott"),
(402, "Benedict Wong"),
(403, "Lucy Hutchinson"),
(404, "Ian Whyte"),
(405, "Branwell Donaghey"),
(406, "Vladimir Furdik"),
(407, "C.C. Smiff"),
(408, "Shane Steyn"),
(409, "John Lebar"),
(410, "Katherine Waterston"),
(411, "Billy Crudup"),
(412, "Danny McBride"),
(413, "Demián Bichir"),
(414, "Carmen Ejogo"),
(415, "Jussie Smollett"),
(416, "Callie Hernandez"),
(417, "Amy Seimetz"),
(418, "Nathaniel Dean"),
(419, "Alexander England"),
(420, "Benjamin Rigby"),
(421, "Uli Latukefu"),
(422, "Tess Haubrich"),
(423, "Andrew Crawford"),
(424, "Guy Pierce"),
(425, "James Franco"),
(426, "Javier Botet"),
(427, "Jake Gyllenhaal Rebecca Ferguson"),
(428, "Ryan Reynolds"),
(429, "Hiroyuki Sanada"),
(430, "Airyon Bakare"),
(431, "Olga Dihovichnaya"),
(432, "Naoko Mori"),
(433, "Haruka Kuroda Camiel Warren-Taylor"),
(434, "Rosamund Pike"),
(435, "Sam Riley"),
(436, "Aneurin Barnard"),
(437, "Simon Russell Beale"),
(438, "Jonathan Aris"),
(439, "Tim Woodward"),
(440, "Katherine Parkinson"),
(441, "Chris O\'Dowd"),
(442, "Richard Ayoade"),
(443, "Matt Berry"),
(444, "Noel Fielding"),
(445, "Peter Serafinowicz"),
(446, "Gragam Linehan"),
(447, "Tom Binns"),
(448, "Lewis Macleod"),
(449, "Gemma Chan"),
(450, "Emily Berrington"),
(451, "Lucy Carless"),
(452, "Colin Morgan"),
(453, "Theo Stevenson"),
(454, "Pixie Daves"),
(455, "Tom Goodman-Hill"),
(456, "Ivanno Jeremiah"),
(457, "Ruth Bradley"),
(458, "Will Tudor"),
(459, "Neil Maskell"),
(460, "Billy Jenkins"),
(461, "Bella Dayne"),
(462, "Thusitha Jayasumdera"),
(463, "Danny Webb"),
(464, "Carrie-Anne Moss"),
(465, "William Hurt"),
(466, "Aaron Paul"),
(467, "Dominic Cooper"),
(468, "Imogen Poots"),
(469, "Ramón Rodríguez"),
(470, "Michael Keaton"),
(471, "Rami Malek"),
(472, "Kid Cudi"),
(473, "Dakota Johnson"),
(474, "Harrison Gilbertson"),
(475, "Carmela Zumbado"),
(476, "Jalil Jay Lynch"),
(477, "Nick Chinlund"),
(478, "Chad Randall"),
(479, "Julianne Nicholson"),
(480, "Jean Smart"),
(481, "Angourie Rice"),
(482, "Evan Peters"),
(483, "Sosie Bacon"),
(484, "David Denman"),
(485, "Neal Huff"),
(486, "James McArdle"),
(487, "John Douglas Thompson"),
(488, "Joe Tippett"),
(489, "Cameron Mann"),
(490, "Chinasa Ogbuagu"),
(491, "Jamie Foxx"),
(492, "Kerry Washington"),
(493, "Regina King"),
(494, "Harry Lennix"),
(495, "Clifton Powell"),
(496, "Bokeem Woodbine"),
(497, "Sharon Warren"),
(498, "C.J. Sanders"),
(499, "Curtis Armstrong"),
(500, "Michaela Coel"),
(501, "Daniel Lapaine"),
(502, "Hannah John-Kamen"),
(503, "Andrew Roux"),
(504, "Claire Keelan"),
(505, "Sinéad Matthews"),
(506, "Anna Wilson-Jones"),
(507, "Paul Popplewell"),
(508, "Julia Davis"),
(509, "Ashely Thomas"),
(510, "Kerrie Hayes"),
(511, "Amy Beth Hayes"),
(512, "Rebekah Staton"),
(513, "Rhashan Stone"),
(514, "Phoebe Fox"),
(515, "Jimi Mistry"),
(516, "Tobias Menzies"),
(517, "Cherry Jones"),
(518, "Alice Eve"),
(519, "Susannah Fielding"),
(520, "Demetri Goritsas"),
(521, "Kadiff Kirwan"),
(522, "Sope Dirisu"),
(523, "Jackson Bews"),
(524, "Annabel Davis"),
(525, "Billy Griffin Jr."),
(526, "Paul Lawrence Kitson"),
(527, "Jeff Mash Patrick Kennedy"),
(528, "Lydia Wilson"),
(529, "Alastair Mackenzie"),
(530, "Chetna Pandya"),
(531, "Tuppence Middleton"),
(532, "Ian Bonar"),
(533, "Elisabeth Hopper"),
(534, "Nick Bartlett"),
(535, "Wunmi Mosaku"),
(536, "Alex Lawther"),
(537, "Jerome Flynn"),
(538, "Susannah Doyle"),
(539, "Madeline Brewer"),
(540, "Ariane Labed"),
(541, "Sarah Snook"),
(542, "Michael Kelly"),
(543, "Jola Bokinni"),
(544, "Faye Marsay"),
(545, "Benefict Wong"),
(546, "Jonas Karlsson"),
(547, "Chloe Pirrie"),
(548, "Eugene O\'Hare"),
(549, "Indira Ainger"),
(550, "James Lance"),
(551, "David Ajala"),
(552, "Sarah Abbott"),
(553, "Jake Davies"),
(554, "Clint Dyer"),
(555, "Letitia Wright"),
(556, "Babs Olusanmokun"),
(557, "Georgina Campbell"),
(558, "Jesse Plemons"),
(559, "Jimmi Simpson"),
(560, "Aldis Hodge"),
(561, "Kiran Sonia Sawar"),
(562, "Miley Cyrus"),
(563, "Anthony Mackie"),
(564, "Nicole Beharie"),
(565, "Gugu Mbatha-Raw"),
(566, "Simona Brown"),
(567, "Eve Hewson"),
(568, "Toma Bateman"),
(569, "Robert Aramayo"),
(570, "Tyler Howitt"),
(571, "Georgie Glen"),
(572, "Kamontip Krissy Ashton"),
(573, "Rob Horrocks"),
(574, "Joakim Skarli"),
(575, "Joaquin Phoenix"),
(576, "Olivia Wilde"),
(577, "Matt Letscher"),
(578, "Portia Doubleday"),
(579, "Spike Jonze"),
(580, "Tom Cruise"),
(581, "Jon Voight"),
(582, "Emmanuelle Béart"),
(583, "Henry Czerny"),
(584, "Jean Reno"),
(585, "Ving Rhames"),
(586, "Kristin Scott Thomas"),
(587, "Vanessa Redgrave"),
(588, "Ingeborga Dapkünaitè"),
(589, "Armie Hammer Alicia Vikander"),
(590, "Elizabeth Debicki"),
(591, "Luca Calvani"),
(592, "Sylvester Groth"),
(593, "Hugh Grant"),
(594, "Christian Berkel"),
(595, "Misha Kuznetsov"),
(596, "Guy Williams"),
(597, "Marianna Di Martino"),
(598, "Dwayne Johnson"),
(599, "Kevin Hart"),
(600, "Jack Black"),
(601, "Karen Gillan"),
(602, "Nick Jonas"),
(603, "Rhys Darby"),
(604, "Bobby Cannavale"),
(605, "Alex Wolff"),
(606, "Ser\'Darius Blain"),
(607, "Madison Iseman"),
(608, "Morgan Turner"),
(609, "Sean Buxton"),
(610, "Mason Guccione"),
(611, "Colin Hanks"),
(612, "Awkwafina"),
(613, "Danny DeVito"),
(614, "Danny Glover"),
(615, "Chris Pine"),
(616, "Robin Wright"),
(617, "Lilly Aspell"),
(618, "Amr Waked"),
(619, "Kristoffer Polaha"),
(620, "Jon Bernthal"),
(621, "Jeffrey Tambor"),
(622, "Cynthia Addai-Robinson"),
(623, "John Lithgow"),
(624, "Andy Umberger"),
(625, "Alison Wright"),
(626, "Daeg Faerch"),
(627, "Seth Lee"),
(628, "Tait Fletcher"),
(629, "Angel Giuffria"),
(630, "Ron Yuan"),
(631, "Scott Hunter"),
(632, "Dennis Keiffer"),
(633, "Jake Presley"),
(634, "Hugh Jackman"),
(635, "Allison Janney"),
(636, "Geraldine Viswanathan"),
(637, "Rafael Casal"),
(638, "Stephen Spinella"),
(639, "Annaleigh Ashford"),
(640, "Ray Romano"),
(641, "Hari Dhillon"),
(642, "Jerremy Shamos"),
(643, "Stephanie Kurtzuba"),
(644, "Catherine Curtin"),
(645, "Kathrine Narducci"),
(646, "Ray Abruzzo"),
(647, "Ben Stiller"),
(648, "Robin Williams"),
(649, "Carla Gugino"),
(650, "Dick Van Dyke"),
(651, "Steve Coogan"),
(652, "Jake Cherry"),
(653, "Mickey Rooney"),
(654, "Bill Cobbs"),
(655, "Owen Wilson"),
(656, "Ricky Gervais"),
(657, "Kim Raver"),
(658, "Mizuo Peck"),
(659, "Gwilym Lee"),
(660, "Ben Hardy"),
(661, "Joseph Mazzello"),
(662, "Lucy Boynton"),
(663, "Aidan Gillen"),
(664, "Tom Hollander"),
(665, "Mike Myers"),
(666, "Julianne Hough"),
(667, "Diego Boneta"),
(668, "Alec Baldwin"),
(669, "Russell Brand"),
(670, "Malin Åkerman"),
(671, "Paul Giamatti"),
(672, "Catherine Zeta-Jones"),
(673, "Mary J. Blige"),
(674, "Erica Frene"),
(675, "Shane Hartline"),
(676, "James Martin Kelly"),
(677, "Will Forte"),
(678, "Eli Roth"),
(679, "Joel Courtney"),
(680, "Elle Fanning"),
(681, "Riley Griffiths"),
(682, "Noah Emmerich"),
(683, "AJ Michalka"),
(684, "Ryan Lee"),
(685, "Ron Eldard"),
(686, "Gabriel Basso"),
(687, "Justice Smith"),
(688, "Daniella Pineda"),
(689, "James Cromwell"),
(690, "Toby Jones"),
(691, "Ted Levine"),
(692, "Jeff Goldblum"),
(693, "BD Wong"),
(694, "Geraldine Chaplin"),
(695, "Isabella Sermon"),
(696, "Kevin Layne"),
(697, "Harrison Ford"),
(698, "Shia LaBeouf"),
(699, "Cate Blanchett"),
(700, "Karen Allen"),
(701, "Ray Winstone"),
(702, "John Hurt"),
(703, "Jim Broadbent"),
(704, "Igor Jijikine"),
(705, "Dimitri Diatchenko"),
(706, "Sean Astin"),
(707, "Josh Brolin"),
(708, "Jeff Cohen"),
(709, "Corey Feldman"),
(710, "Kerri Green"),
(711, "Martha Plimpton"),
(712, "Jonathan Ke Quan"),
(713, "Jogn matuszak"),
(714, "Robert Davi"),
(715, "Bonnie Hunt"),
(716, "Paul Newman"),
(717, "Larry the Cable Guy"),
(718, "Tony Shalhoub"),
(719, "Cheech Marin"),
(720, "Michael Wallis"),
(721, "George Carlin"),
(722, "Paul Dooley"),
(723, "Chris Miller"),
(724, "Tom McGrath Danny Jacobs"),
(725, "Andy Richter"),
(726, "Nicole Sullivan Christopher Knights"),
(727, "Wayne Knight"),
(728, "Dale Midkiff"),
(729, "Fred Gwynne"),
(730, "Denise Crosby"),
(731, "Brad Greenquist"),
(732, "Michael Lombard"),
(733, "Miko Hughes"),
(734, "Blaze Berdahl"),
(735, "Susan Blommaert"),
(736, "Mara Clark"),
(737, "Craig T. Nelson"),
(738, "JoBeth Williams"),
(739, "Beatrice Straight"),
(740, "Dominique Dunne"),
(741, "Oliver Robins"),
(742, "Heather O\'Rourke"),
(743, "Michael McManus"),
(744, "Virginia Kiser"),
(745, "Martin Casella"),
(746, "Audrey Tautou"),
(747, "Ian McKellen"),
(748, "Alfred Molina"),
(749, "Jürgen Prochnow"),
(750, "Jean-Yves Berteloot"),
(751, "Etienne Chicot"),
(752, "Rowan Atkinson"),
(753, "Natalie Imbruglia"),
(754, "Ben Miller"),
(755, "John Malkovich"),
(756, "Greg Wise"),
(757, "Tasha de Vasconcelos"),
(758, "Douglas McFerran"),
(759, "Steve Nicolson"),
(760, "Terence Harvey"),
(761, "Frances McDormand"),
(762, "Kate Hudson"),
(763, "Jason Lee"),
(764, "Zoey Deschanel"),
(765, "Michael Angarano"),
(766, "Anna Paquin"),
(767, "Fairuzza Balk"),
(768, "Joan Cusack"),
(769, "Mike White"),
(770, "Sarah Silverman"),
(771, "Lee Wilkof"),
(772, "Kate McGregor-Stewart"),
(773, "Adam Pascal"),
(774, "Suzzane Douglas"),
(775, "Macaulay Culkin"),
(776, "Joe Pesci"),
(777, "Daniel Stern"),
(778, "John Heard"),
(779, "Catherine O\'Hara"),
(780, "Roberts Blossom"),
(781, "Devin Ratray"),
(782, "Michael C. Maronna"),
(783, "Hillary Wolf"),
(784, "Vince Vaughn"),
(785, "Will Ferrell"),
(786, "Rose Byrne"),
(787, "Aasif Mandvi"),
(788, "Josh Brener"),
(789, "Dylan O\'Brien"),
(790, "Tiya Sircar"),
(791, "Tobit Raphael"),
(792, "Jessica Szohr"),
(793, "Rob Riggle"),
(794, "Eric André"),
(795, "Harvey Guillén"),
(796, "Gary Anthony Williams"),
(797, "Bruno Amato"),
(798, "Karen Ceesay"),
(799, "John Goodman"),
(800, "Rebecca Hazlewood"),
(801, "Sacha Dhawan"),
(802, "Diedrich Bader"),
(803, "Pippa Black"),
(804, "Parvesh Ceena"),
(805, "Thushari Jayasekera"),
(806, "Ben Rappaport"),
(807, "Guru Singh"),
(808, "Rizwan Manji"),
(809, "Anisha Nagarajan"),
(810, "Carla Gallo"),
(811, "Radhika Chaudhari"),
(812, "Nicholas Logan"),
(813, "Blake Lively"),
(814, "Óscar Jaenada"),
(815, "Janelle Bailley"),
(816, "Chelsea Moody"),
(817, "Angelo Josue Lozano Corzo"),
(818, "José Manuel Trujillo Salas"),
(819, "Brett Cullen"),
(820, "Sedona Legge"),
(821, "Pablo Calva"),
(822, "Jake Gyllenhaal"),
(823, "Jogn Hawkes"),
(824, "Sam Worthington"),
(825, "Emily Watson"),
(826, "Martin Henderson"),
(827, "Thomas M. Wright"),
(828, "Clive StandenNaoko Mori"),
(829, "Mia Goth"),
(830, "Vanessa Kirby"),
(831, "Raúl Juliá"),
(832, "Anjelica Huston"),
(833, "Christopher Lloyd"),
(834, "Christina Ricci"),
(835, "Carel Struycken"),
(836, "Dan Hedaya"),
(837, "Jimmy Workman"),
(838, "Elizabeth Wilson"),
(839, "Dana Ivey");


-- Tabla contenidos

INSERT INTO `contenidos`( `poster`, `titulo`, `categoriaID`, `generoID`, `resumen`, `temporadas`, `duracion`, `trailer`) VALUES /* en original dice: INSERT INTO `Trailers`( `poster`, `titulo`, `categoria_id`, `genero_id`, `resumen`, `temporadas`, `duracion`, `trailer`) VALUES */
("./posters/1.jpg","The Crown","2","3","Este drama narra las rivalidades políticas y el romance de la reina Isabel II, así como los sucesos que moldearon la segunda mitad del siglo XX.","4","https://www.youtube.com/embed/JWtnJjn6ng0",NULL),
("./posters/2.jpg","Riverdale","2","2","El paso a la edad adulta incluye sexo, romance, escuela y familia. Para Archie y sus amigos, también hay misterios oscuros.","5","https://www.youtube.com/embed/HxtLlByaYTc",NULL),
("./posters/3.jpg","The Mandalorian","2","1","Ambientada tras la caída del Imperio y antes de la aparición de la Primera Orden, la Serie sigue los pasos de un pistolero solitario en las aventuras que protagoniza en los confines de la galaxia, donde no alcanza la autoridad de la Nueva República.","2","https://www.youtube.com/embed/aOC8E8z_ifw",NULL),
("./posters/4.jpg","The Umbrella Academy","2","1","La muerte de su padre reúne a unos hermanos distanciados y con extraordinarios poderes que descubren impactantes secretos y una amenaza que se cierne sobre la humanidad.","1","https://www.youtube.com/embed/KHucKOK-Vik",NULL),
("./posters/5.jpg","Gambito de Dama","2","2","En los cincuenta, una joven de un orfanato descubre que tiene un increíble don para el ajedrez y recorre el arduo camino a la fama mientras lucha contra las adicciones.","1","https://www.youtube.com/embed/lbleRbyGKL4",NULL),
("./posters/6.jpg","Enola Holmes","1","2","La hermana menor de Sherlock, descubre que su madre ha desaparecido y se dispone a encontrarla. En su búsqueda, saca a relucir el sabueso que corre por sus venas y se encuentra con una conspiración que gira en torno a un misterioso lord, demostrando que su ilustre hermano no es el único talento en la familia.",NULL,"https://www.youtube.com/embed/3t1g2pa355k","97 minutos"),
("./posters/7.jpg","Guasón","1","4","Arthur Fleck (Phoenix) es un hombre ignorado por la sociedad, cuya motivación en la vida es hacer reír. Pero una Serie de trágicos acontecimientos le llevarán a ver el mundo de otra forma. Película basada en el popular personaje de DC Comics Joker, conocido como archivillano de Batman, pero que en este film tomará un cariz más realista y oscuro.",NULL,"https://www.youtube.com/embed/zAGVQLHvwOY","97 minutos"),
("./posters/8.jpg","Avengers: End Game","1","1","Después de los devastadores eventos de los Vengadores: Infinity War (2018), el universo está en ruinas. Con la ayuda de los aliados restantes, los Vengadores se reúnen una vez más para revertir las acciones de Thanos y restaurar el equilibrio del universo.",NULL,"https://www.youtube.com/embed/TcMBFSGVi1c","97 minutos"),
("./posters/9.jpg","Juego de tronos","2","10","En un mundo fantástico y en un contexto medieval varias familias, relativas a la nobleza, se disputan el poder para dominar el territorio ficticio de Poniente (Westeros) y tomar el control de los Siete Reinos desde el Trono de Hierro, lugar donde el rey ejerce el poder.","8","https://www.youtube.com/embed/KPLWWIOCOOQ",NULL),
("./posters/10.jpg","The Flash","2","1","Sigue las veloces aventuras de Barry Allen, un joven común y corriente con el deseo latente de ayudar a los demás. Cuando una inesperada partícula aceleradora golpea por accidente a Barry, de pronto se encuentra cargado de un increíble poder para moverse a increíbles velocidades. Mientras Barry siempre ha tenido el alma de un héroe, sus nuevos poderes le han dado la capacidad de actuar como tal.","6","https://www.youtube.com/embed/Yj0l7iGKh8g",NULL),
("./posters/11.jpg","The Big Bang Theory","2","5","Leonard y Sheldon son dos físicos que comparten trabajo y apartamento. La Serie comienza con la mudanza de Penny, su nueva y atractiva vecina, y hace hincapié en la dificultad de los físicos para relacionarse con personas fuera de su entorno para dar lugar a situaciones cómicas.","12","https://www.youtube.com/embed/WBb3fojgW0Q",NULL),
("./posters/12.jpg","Friends","2","5","'Friends' narra las aventuras y desventuras de seis jóvenes de Nueva York: Rachel, Monica, Phoebe, Ross, Chandler y Joey. Ellos forman una unida pandilla de amigos que viven en Manhattan y que suelen reunirse en sus apartamentos o en su bar habitual cafetería, el Central Perk. A pesar de los numerosos cambios que se producen en sus vidas, su amistad es inquebrantable en la dura batalla por salir adelante en sus periplos profesionales y personales.","10","https://www.youtube.com/embed/ekYGfU0XIx0",NULL),
("./posters/13.jpg","Anne with an 'E'","2","6","Anne Shirley es una niña huérfana que vive en un pequeño pueblo llamado Avonlea que pertenece a la Isla del Príncipe Eduardo, en el año 1890. Después de una infancia difícil, donde fue pasando de orfanato a hogares de acogida, es enviada por error a vivir con una solterona y su hermano. Cuando cumple 13 años, Anne va a conseguir transformar su vida y el pequeño pueblo donde vive gracias a su fuerte personalidad, intelecto e imaginación. Basada en la inolvidable novela.","2","https://www.youtube.com/embed/M4T-_aB8smU",NULL),
("./posters/14.jpg","Expedientes Secretos 'X'","2","1","Fox Mulder y Dana Scully son dos investigadores del FBI que investigan casos sin resolución ni explicación, ya sea por razones paranormales (espíritus, criaturas extrañas, aliens...) ya porque el gobierno se ha encargado de ocultar todo tipo de pruebas. Cuando Mulder tenía doce años, su hermana pequeña fue secuestrada por unos desconocidos, aunque él cree que, en realidad, fue abducida por extraterrestres. Tras acabar sus estudios en la universidad de Oxford, ingresó en la Academia de Quantico, donde se ganó el apodo de 'siniestro'","11","https://www.youtube.com/embed/KKziOmsJxzE",NULL),
("./posters/15.jpg","Chernobyl","2","3","Sigue «la verdadera historia de una de las peores catástrofes provocadas por el hombre y habla de los valientes hombres y mujeres que se sacrificaron para salvar a Europa de un desastre inimaginable. La miniSerie se centra en el desgarrador alcance del desastre de la planta nuclear que ocurrió en Ucrania en abril de 1986, revelando cómo y por qué ocurrió, además contando las sorprendentes y notables historias de los héroes que lucharon y cayeron.","1","https://www.youtube.com/embed/s9APLXM9Ei8",NULL),
("./posters/16.jpg","Westworld","2","1","'Westworld' es una oscura odisea acerca del amanecer de la conciencia artificial y la evolución del pecado. Situada en la intersección del futuro cercano y el pasado reimaginado, explora un mundo donde cada apetito humano, sin importar cuán noble o depravado, puede ser saciado. Está ambientada en un parque temático futurista dirigido por el Dr. Robert Ford (Anthony Hopkins). Las instalaciones cuentan con androides caracterizados del western americano, y gracias a ellos los visitantes pueden introducirse en cualquier tipo de fantasía por muy oscura que sea.","3","https://www.youtube.com/embed/qLFBcdd6Qw0",NULL),
("./posters/17.jpg","Halt and Catch Fire","2","2","","4","https://www.youtube.com/embed/pWrioRji60A",NULL),
("./posters/18.jpg","Ava","1","8","Ava es una mortífera asesina a sueldo que trabaja para una organización de operaciones encubiertas, que viaja por todo el mundo acabando con aquellos objetivos que nadie más puede derribar. Cuando uno de sus encargos sale mal, Ava tendrá que luchar por una vida.",NULL,"https://www.youtube.com/embed/eLEwNo78f0k","97 minutos"),
("./posters/19.jpg","Aves de presa y la fantabulosa emancipación de una Harley Quinn","1","1","Después de separarse de Joker, Harley Quinn y otras tres heroínas (Canario Negro, Cazadora y Renée Montoya) unen sus fuerzas para salvar a una niña (Cassandra Cain) del malvado rey del crimen Máscara Negra.",NULL,"https://www.youtube.com/embed/saUmnenKbBM","97 minutos"),
("./posters/20.jpg","Archivo","1","1","2038: George Almore está trabajando en una verdadera IA equivalente a la humana. Su último prototipo está casi listo. Esta fase sensible también es la más arriesgada. Especialmente porque tiene un objetivo que debe ocultarse a toda costa: reunirse con su esposa muerta.",NULL,"https://www.youtube.com/embed/VHSoCnDioAo","97 minutos"),
("./posters/22.jpg","3022","1","4","La película está ambientada en una estación espacial en el futuro. La tripulación sufre un estrés traumático y considera abandonar su misión después de observar lo que creen que es la destrucción de la Tierra. La película se muestra como una Serie de flashbacks y flash-forward.",NULL,"https://www.youtube.com/embed/AGQ7OkmIx4Q","97 minutos"),
("./posters/23.jpg","IT - Capítulo 2","1","7","En este segundo capitulo Han pasado 27 años desde que el 'Club de los Perdedores', formado por Bill, Berverly, Richie, Ben, Eddie, Mike y Stanley, se enfrentaran al macabro y despiadado Pennywise (Bill Skarsgård). En cuanto tuvieron oportunidad, abandonaron el pueblo de Derry, en el estado de Maine, que tantos problemas les había ocasionado. Sin embargo, ahora, siendo adultos, parece que no pueden escapar de su pasado. Todos deberán enfrentarse de nuevo al temible payaso para descubrir si de verdad están preparados para superar sus traumas de la infancia.",NULL,"https://www.youtube.com/embed/hZeFeYSmBcg","97 minutos"),
("./posters/24.jpg","Pantera Negra","1","1","T’Challa (Chadwick Boseman) regresa a su hogar en la apartada nación africana de Wakanda para servir como líder de su país. Tras suceder a su padre en el trono, pasa a convertirse en Pantera Negra, una sigilosa criatura de la noche, con agudos sentidos felinos y otras habilidades como súper fuerza e inteligencia, agilidad, estrategia o maestro del combate sin armas. Es bajo el liderazgo de T’Challa como Wakanda consigue convertirse en una de las naciones más ricas y tecnológicamente avanzadas del planeta.",NULL,"https://www.youtube.com/embed/BE6inv8Xh4A","97 minutos"),
("./posters/25.jpg","Contra lo imposible (Ford versus Ferrari)","1","3","Los ganadores del Premio de la Academia® Matt Damon y Christian Bale protagonizan CONTRA LO IMPOSIBLE, basada en la historia real del visionario diseñador americano de automóviles Carroll Shelby (Damon) y el intrépido piloto británico Ken Miles (Bale). Juntos construyen un nuevo coche de carreras para Ford Motor Company y así enfrentar a Enzo Ferrari en las 24 Horas de Le Mans en Francia en 1966.",NULL,"https://www.youtube.com/embed/SOVb0-2g1Q0","97 minutos"),
("./posters/26.jpg","Centígrados","1","4","Una joven pareja estadounidense viaja a las montañas árticas de Noruega. Después de detenerse durante una tormenta de nieve, se despiertan atrapados en su SUV, enterrados bajo capas de nieve y hielo.",NULL,"https://www.youtube.com/embed/0RvV7TNUlkQ","97 minutos"),
("./posters/27.jpg","DOOM: Aniquilación","1","7","Doom: Aniquilación sigue a un grupo de marines espaciales que han respondido a una llamada de alerta de una base en la luna marciana, solo para descubrir que ha sido tomada por criaturas demoníacas que amenazan con desatar el infierno en la tierra.",NULL,"https://www.youtube.com/embed/nat3u3gAVLE","97 minutos"),
("./posters/28.jpg","Contagio","1","2","De repente, sin saber cuál es su origen, aunque todo hace sospechar que comienza con el viaje de una norteamericana a un casino de Hong Kong, un virus mortal comienza a propagarse por todo el mundo. En pocos días, la enfermedad empieza a diezmar a la población. El contagio se produce por mero contacto entre los seres humanos. Un thriller realista y sin efectos especiales sobre los efectos de una epidemia.",NULL,"https://www.youtube.com/embed/4sYSyuuLk5g","97 minutos"),
("./posters/29.jpg","Viuda Negra","1","9","Primera pelicula individual de la Viuda Negra en el universo cinematografico de Marvel, contando su historia desde que se inició como doble agente rusa, su niñez, sus misiones, y su actualidad, después de Avengers.",NULL,"https://www.youtube.com/embed/BIn8iANwEog","97 minutos"),
("./posters/30.jpg","The Martian","1","1","Durante una misión a Marte de la nave tripulada Ares III, una fuerte tormenta se desata dando por desaparecido y muerto al astronauta Mark Watney (Matt Damon), sus compañeros toman la decisión de irse pero él ha sobrevivido. Está solo y sin apenas recursos en el planeta. Con muy pocos medios deberá recurrir a sus conocimientos, su sentido del humor y un gran instinto de supervivencia para lograr sobrevivir y comunicar a la Tierra que todavía está vivo esperando que acudan en su rescate.",NULL,"https://www.youtube.com/embed/XvB58bCVfng","97 minutos"),
("./posters/31.jpg","Ex-Machina","1","1","Un programador multimillonario selecciona a Caleb, un joven empleado de su empresa, para que pase una semana en un lugar remoto con el objetivo de que participe en un test en el que estará involucrada su última creación: un robot-mujer en el que inteligencia artificial lo es todo.",NULL,"https://www.youtube.com/embed/XRYL5spvEcI","97 minutos"),
("./posters/32.jpg","Jurassic World","1","8","Veintidós años después de lo ocurrido en Jurassic Park, la isla Nublar ha sido transformada en un enorme parque temático, Jurassic Wold, con versiones «domesticadas» de algunos de los dinosaurios más conocidos. Cuando todo parece ir sobre ruedas y ser el negocio del siglo, un nuevo dinosaurio de especie desconocida, pues ha sido creado manipulando genéticamente su ADN, y que resulta ser mucho más inteligente de lo que se pensaba, se escapa de su recinto y comienza a causar estragos entre los visitantes del Parque.",NULL,"https://www.youtube.com/embed/RFinNxS5KN4","97 minutos"),
("./posters/33.jpg","Soy leyenda","1","7","Años después de que una plaga mate a la mayoría de la humanidad y transforme al resto en monstruos, el único superviviente en la ciudad de Nueva York lucha valientemente para encontrar una cura.",NULL,"https://www.youtube.com/embed/dtKMEAXyPkg","97 minutos"),
("./posters/34.jpg","El primer hombre en la luna","1","3","Cuenta la historia de la misión de la NASA que llevó al primer hombre a la luna, centrada en Neil Armstrong (interpretado por Ryan Gosling) y el periodo comprendido entre los años 1961 y 1969. Un relato en primera persona, basado en la novela de James R. Hansen, que explora el sacrificio y el precio que representó, tanto para Armstrong como para Estados Unidos, una de las misiones más peligrosas de la historia.",NULL,"https://www.youtube.com/embed/PSoRx87OO6k","97 minutos"),
("./posters/35.jpg","Titanes del pacífico - La insurrección","1","1","Han pasado 10 años tras la primera invasión que sufrió la humanidad, pero la lucha aún no ha terminado. El planeta vuelve a ser asediado por los Kaiju, una raza de alienígenas colosales, que emergen desde un portal interdimensional con el objetivo de destruir a la raza humana. Ante esta nueva amenaza, los Jaegers, robots gigantes de guerra pilotados por dos personas para sobrellevar la inmensa carga neuronal que conlleva manipularlos, ya no están a la altura de lo que se les viene encima. Será entonces cuando los supervivientes de la primera invasión, además de nuevos personajes como el hijo de Pentecost, tendrán que idear la manera de sorprender al enorme enemigo, apostando por nuevas estrategias defensivas y de ataque. Con la Tierra en ruinas e intentando reconstruirse, esta nueva batalla puede ser decisiva para el futuro.",NULL,"https://www.youtube.com/embed/_EhiLLOhVis","97 minutos"),
("./posters/36.jpg","JOBS: La Vida De Steve Jobs","1","3","Sólo hace falta una persona para empezar una revolución. Jobs es la extraordinaria historia de Steve Jobs, el original innovador y emprendedor que no dejó que nada se interpusiera en su camino hacia la grandeza. La película cuenta la épica y turbulenta historia de Jobs mientras abría un camino que cambió la tecnología - y el mundo - para siempre. Su vida es repasada desde que era adolescente, intentando estudiar en la universidad, hasta el año 2001, cuando el iPod fue presentado al mundo y comenzó a 'allanar' el camino para lo que años después, sería el iPhone.",NULL,"https://www.youtube.com/embed/FrvkCS0ZGPU","104 minutos"),
("./posters/37.jpg","Piratas de Silicon Valey","1","3","Esta película es el documental semigracioso sobre los hombres que hicieron el mundo de la tecnología lo que es hoy, sus luchas durante el colegio, la fundación de sus compañías y las acciones ingeniosas que tomaron para aumentar los Imperios corporativos globales de Apple Computer Inc. y Microsoft Corporation.",NULL,"https://www.youtube.com/embed/lEyrivrjAuU","104 minutos"),
("./posters/38.jpg","Red Social","1","3","En una noche de otoño de 2003, el genio de la programación de computación de la Universidad de Harvard Mark Zuckerberg se sienta en su computadora y acaloradamente comienza a trabajar en una nueva idea. En una furia de los blogs y la programación, lo que comienza en su dormitorio como un pequeño sitio entre amigos pronto se convierte en una red social global y una revolución en la comunicación. A sólo seis años y 500 millones de amigos más tarde, Mark Zuckerberg es el multimillonario más joven de la historia ... pero para este empresario, el éxito conduce a complicaciones tanto personales como legales.",NULL,"https://www.youtube.com/embed/lB95KLmpLR4","116 minutos"),
("./posters/39.jpg","Antitrust","1","9","Milo Hoffman es un joven informático increíblemente prometedor para su edad que rápidamente es contratado por una importante empresa de Sillicon Valley. El empleo de sus sueños se ha hecho realidad, ya que ahí puede trabajar con los ordenadores más potentes del mundo y con las últimas tecnologías que aún no han salido al mercado. El Paraíso de un informático. Su jefe, Gary Winston , es un poderoso pez gordo de la industria que en un principio parece un tipo íntegro y legal. Pero pronto descubrirá que fisgar en sus archivos secretos no es la mejor idea si uno quiere conservar su trabajo... y su vida.",NULL,"https://www.youtube.com/embed/k3TwIJjyjPM","110 minutos"),
("./posters/40.jpg","Stowaway","1","1","Una misión al planeta Marte. Dos años de duración. De repente, los tres tripulantes afectados a esta labor deben tomar una decisión imposible cuando un pasajero imprevisto compromete la vida de todos a bordo. No hay vuelta atrás. La decisión deberá tomarse contemplando la vida de los, ahora, cuatro pasajeros aún cuando la supervivecnaia tenga que acarrear algún sacrificio.",NULL,"https://www.youtube.com/embed/A_apvQkWsVY","118 minutos"),
("./posters/41.jpg","Liga de la Justicia - Zack Snyder","1","9","Decidido a asegurarse de que el sacrificio final de Superman no fue en vano, Bruce Wayne alinea fuerzas con Diana Prince con planes para reclutar un equipo de metahumanos para proteger al mundo de una amenaza de proporciones catastróficas que se aproxima. En esta fascinante entrega, no apta para niños, verás cómo se conforma la Liga de la Justicia, uniendo a los principales superhéroes conocidos como Metahumanos.",NULL,"https://www.youtube.com/embed/BUb_-RxsoBs","242 minutos"),
("./posters/42.jpg","Two and a half men","2","5","Un quiropráctico y padre soltero, Alan Harper, vive en una casa al frente de la playa con su hijo mediocre, Jake, y un billonario de la Internet divorciado Walden Schmidt, que se muda con la familia de los Harper y ofrece comprar la casa luego de la muerte inesperada del hermano de Alan, Charlie, que era el propietario de la casa en la que vivía con Alan y Jake, luego de que padre e hijo se mudaran después del divorcio de Alan. La exesposa de Alan y madre de Jake, Judith, permanece en sus vidas.","12","https://www.youtube.com/embed/mVHDanSl2pc",NULL),
("./posters/43.jpg","La casa de Papel","2","9","Ocho ladrones toman rehenes en la Fábrica Nacional de Moneda y Timbre de España, mientras el líder de la banda manipula a la policía para cumplir con su plan.","4","https://www.youtube.com/embed/w1jkStuRQU8",NULL),
("./posters/44.jpg","Stranger Things","2","4","Pasan cosas muy extrañas en Hawkins, Indiana, tras una desaparición que revela la presencia de una niña con poderes sobrenaturales. Después de la extraña desaparición de un niño, un pueblo se encuentra ante un misterio que revela experimentos secretos, fuerzas sobrenaturales.","4","https://www.youtube.com/embed/b9EkMc79ZSU",NULL),
("./posters/45.jpg","Gravity","1","4","Durante un paseo espacial rutinario, dos astronautas sufren un grave accidente y quedan flotando en el espacio. Una es la doctora Ryan Stone, una brillante ingeniera en su primera misión espacial en la Shuttle. Su acompañante es el veterano astronauta Matt Kowalsky. Durante el paseo algo sale mal y ocurre el desastre: el shuttle queda destrozado, dejando a Ryan y Matt completamente solos, momento a partir del cual intentarán por todos los medios volver a la Tierra.", NULL,"https://www.youtube.com/embed/OiTiKOy59o4","93 minutos"),
("./posters/49.jpg","It (eso)","1","7","Remake del clásico de Stephen King, y de la película homónima de 1990, en el que un payaso aterroriza a los niños de un vecindario. En un pequeño pueblo de Maine, siete niños conocidos como el Club de los Perdedores se encuentran cara a cara con problemas de la vida, matones y un monstruo que toma la forma de un payaso llamado Pennywise..",NULL,"https://www.youtube.com/embed/FnCdOQsX5kc","135 minutos"),
("./posters/46.jpg","Apollo 13","1","3","El Apolo 13 inicia su viaje a la luna en abril de 1970. Cuando la tripulación está a punto de llegar a su destino, una explosión en el espacio les hace perder oxígeno, energía y el curso de la nave... Todo se convierte en una situación desesperada para los tres hombres tripulantes, especialmente cuando el oxígeno amenaza con agotarse. Mientras, el mundo entero, que apenas un año antes conoció la gloria de la aventura espacial cuando el hombre pisó la luna, contiene la respiración a la espera de ver cómo acaba tan angustiosa espera.", NULL,"https://www.youtube.com/embed/e3ZtOS4MCkk","140 minutos"),
("./posters/47.jpg","La profecía","1","7","Incapaz de decirle a su mujer Katherine la trágica muerte de su hijo recién nacido, el diplomático americano Robert Thorn acepta un huérfano como su hijo. Los detalles del nacimiento del chico son un secreto, pero cuando Damien va creciendo, empieza a dar muestras de que no es un chico corriente.",NULL,"https://www.youtube.com/embed/8L-1Qk_MQQs","110 minutos"),
("./posters/48.jpg","El exorcista","1","7","Regan es una niña de doce años víctima de fenómenos paranormales como la levitación o la manifestación de una fuerza sobrehumana. Su madre, aterrorizada, tras someter a su hija a múltiples análisis médicos que no ofrecen ningún resultado, acude a un sacerdote con estudios de psiquiatría. Éste está convencido de que el mal no es físico sino espiritual, es decir, que la niña es víctima de una posesión diabólica. Por eso, con la ayuda de otro sacerdote decide practicar un exorcismo.",NULL,"https://www.youtube.com/embed/YDGw1MTEe9k","122 minutos"),
("./posters/50.jpg","The Office","2","5","Steve Carell protagoniza The Office, un fresco y divertido vistazo, con formato pseudo-documental, al día a día en la vida de unos excéntricos trabajadores de la empresa Dunder Mifflin. El serio pero despistadísimo director Michael Scott se considera un magnífico jefe y mentor, pero realmente inspira más críticas que respeto a sus empleados.","9","https://www.youtube.com/embed/LHOtME2DL4g",NULL),
("./posters/51.jpg","The Good Doctor","2","6","Un cirujano joven y autista que padece el síndrome del sabio empieza a trabajar en un hospital prestigioso. Allá tendrá que vencer el escepticismo con el que sus colegas lo reciben.","4","https://www.youtube.com/embed/fYlZDTru55g",NULL),
("./posters/52.jpg","La teoría del todo","1","3","La película gira en torno a la vida de Stephen Hawking, el importante teórico y divulgador científico que cambió la historia de la ciencia y la tecnología moderna para siempre. La película se centrará en la relación que mantuvo el británico con Jane Wilde, su primera mujer, con quien contrajo matrimonio después de que le diagnosticaran una enfermedad por la que no le quedaban más de dos años de vida. Estupenda adaptación con un Eddie Redmayne que cada día nos sorprende más.",NULL,"https://www.youtube.com/embed/Salz7uGp72c","123 minutos"),
("./posters/53.jpg","Código enigma","1","3","Durante el invierno de 1952, las autoridades británicas entraron en el hogar del matemático, analista y héroe de guerra Alan Turing, con la intención de investigar la denuncia de un robo. Al final acabaron arrestando a Turing acusándole de indecencia grave, un cargo que le supondría una devastadora condena por una ofensa criminal: ser homosexual. Los oficiales no tenían ni idea de que en realidad estaban incriminando al pionero de la informática actual. Liderando a un heterogéneo grupo de académicos, lingüistas, campeones de ajedrez y oficiales de inteligencia, se le conoce por haber descifrado el código de la inquebrantable máquina Enigma de los alemanes durante la Segunda Guerra Mundial.",NULL,"https://www.youtube.com/embed/nuPZUUED5uk","115 minutos"),
("./posters/54.jpg","Talentos ocultos","1","3","Narra la historia nunca contada de tres brillantes mujeres científicas afroamericanas que trabajaron en la NASA a comienzos de los años sesenta (en plena carrera espacial, y asimismo en mitad de la lucha por los derechos civiles de los negros estadounidenses) en el ambicioso proyecto de poner en órbita al astronauta John Glenn.",NULL,"https://www.youtube.com/embed/RK8xHq6dfAo","127 minutos"),
("./posters/55.jpg","Una mente brillante","1","3","Obsesionado con la búsqueda de una idea matemática original, el brillante estudiante John Forbes Nash llega a Princeton para realizar sus estudios de postgrado. Es un muchacho extraño y solitario, al que sólo comprende su compañero de cuarto. Por fin, Nash esboza una revolucionaria teoría y consigue una plaza de profesor en el MIT. Alicia Lardé, una de sus alumnas, lo deja fascinado al mostrarle que las leyes del amor están por encima de las de las matemáticas. Gracias a su prodigiosa habilidad para descifrar códigos es reclutado por Parcher William, del departamento de Defensa, para ayudar a los Estados Unidos en la Guerra Fría contra la Unión Soviética.",NULL,"https://www.youtube.com/embed/jT51irTIrAc","134 minutos"),
("./posters/56.jpg","Passengers","1","1","Una nave espacial, que viaja a un planeta lejano transportando a miles de personas, tiene una avería en una de las cápsulas de hibernación tras el impacto con un gran meteorito. Como resultado, un pasajero se despierta noventa años antes del final del viaje.",NULL,"https://www.youtube.com/embed/7BWWWQzTpNU","116 minutos"),
("./posters/57.jpg","Passengers","1","4","Un avión se estrella y tan sólo sobreviven cinco personas. Asignada al caso por su mentor, la joven terapeuta Claire, una brillante psicóloga, deberá ayudar a los supervivientes a superar el trauma. Pero, poco a poco, éstos empiezan a desaparecer misteriosamente... o a no aparecer en la sesiones. Nada está claro, ni siquiera qué pasó en el accidente. Además, entre los supervivientes está Eric, un atractivo pasajero que parece no necesitar terapia. (la línea entre este mundo y el próximo, está a pundo de ser cruzada)",NULL,"https://www.youtube.com/embed/iMW4RpQmJJQ","93 minutos"),
("./posters/58.jpg","Argo","1","3","Irán, año 1979. Cuando la embajada de los Estados Unidos en Teherán es ocupada por seguidores del Ayatolá Jomeini para pedir la extradición del Sha de Persia, la CIA y el gobierno canadiense organizaron una operación para rescatar a seis diplomáticos estadounidenses que se habían refugiado en la casa del embajador de Canadá. Con este fin se recurrió a un experto en rescatar rehenes y se preparó el escenario para el rodaje de una película de ciencia-ficción, de título 'Argo', en la que participaba un equipo de cazatalentos de Hollywood. La misión: ir a Teherán y hacer pasar a los diplomáticos por un equipo de filmación canadiense para traerlos de vuelta a casa.",NULL,"https://www.youtube.com/embed/JW3WfSFgrVY","120 minutos"),
("./posters/59.jpg","Prometheus","1","1","Un grupo de científicos y exploradores emprende un viaje espacial a un remoto planeta, una rara estrella recién descubierta, donde sus límites físicos y mentales serán puestos a prueba. El motivo de la misión es que los humanos creen que allá podrán encontrar la respuesta a las preguntas más profundas y al mayor de los misterios: el origen de la vida en la Tierra.",NULL,"https://www.youtube.com/embed/34cEo0VhfGE","120 minutos"),
("./posters/60.jpg","Alien: Covenant","1","1","Rumbo a un remoto planeta al otro lado de la galaxia, la tripulación de la nave colonial Covenant descubre lo que creen que es un paraíso inexplorado, pero resulta tratarse de un mundo oscuro y hostil cuyo único habitante es un 'sintético' llamado David (Michael Fassbender), superviviente de la malograda expedición Prometheus. Secuela de 'Prometheus' (2012), a su vez precuela de 'Alien, el octavo pasajero' (1979).",NULL,"https://www.youtube.com/embed/svnAD0TApb8","122 minutos"),
("./posters/61.jpg","Life: Vida inteligente","1","4","Seis miembros de la tripulación de la Estación Espacial Internacional que están a punto de lograr uno de los descubrimientos más importantes en la historia humana: la primera evidencia de vida extraterrestre en Marte. A medida que el equipo comienza a investigar y sus métodos tienen consecuencias inesperadas, la forma viviente demostrará ser más inteligente de lo que cualquiera esperaba.",NULL,"https://www.youtube.com/embed/viX9irZw9Cg","106 minutos"),
("./posters/62.jpg","Madame Curie","1","3","Basada en el libro 'A tale of love and fallout' de Lauren Redniss, Radioactive es la historia biográfica sobre la científica polaca Marie Curie, la primera persona en recibir dos premios Nobel en distintas especialidades —Física y Química—, y la primera mujer en ocupar el puesto de profesora en la Universidad de París. Dirigida por Marjane Satrapi y protagonizada por Rosamund Pike como Marie Curie, está basada en la novela gráfica de Lauren Redniss.",NULL,"https://www.youtube.com/embed/w0jqppl-ybY","115 minutos"),
("./posters/63.jpg","The IT Crowd","2","5","En un desordenado sótano en las entrañas de Industrias Reynholm habitan Roy y Moss, los componentes del Departamento de informática. Víctimas del desprecio y del escarnio de sus compañeros más guays, su mundo de servidores y cortafuegos se ve interrumpido por la llegada de Jen, su nueva jefa, que sabe tanto de ordenadores como un yak.","4","https://www.youtube.com/embed/wCa1jfo93jQ",NULL),
("./posters/64.jpg","Humans","2","1","En un presente paralelo donde el último gadget que hay que tener para cualquier familia ocupada es un 'Synth' - un sirviente robótico altamente desarrollado que es tan similar a un humano real que está transformando la manera en que vivimos.","3","https://www.youtube.com/embed/BV8qFeZxZPE",NULL),
("./posters/65.jpg","Need for Speed","1","9","El más famoso de los videojuegos de carreras llega a la gran pantalla para dejar a los más fanáticos boquiabiertos. Need for Speed cuenta la historia de un experto en automovilismo (Aaron Paul), el cual tiene un garage en dónde transforma coches para hacerlos más rápidos de lo que son para poder competir en carreras ilegales. Entró en la cárcel por un delito que no había cometido, justo cuando su mejor amigo muere en una carrera, y ahora sale de allí para vengarse.",NULL,"https://www.youtube.com/embed/u3wtVI-aJuw","130 minutos"),
("./posters/66.jpg","Mare of Easttown","2","2","Mare of Easttown es una miniserie estadounidense de drama y misterio creada por Brad Ingelsby cuenta la historia de Mare Sheehan, una detective de un pequeño pueblo de Pensilvania que investiga un asesinato local mientras trata de evitar que su vida se desmorone a raiz de la muerte de su hijo, su separación, y la posible restitución de su nieto a su madre biológica.","1","https://www.youtube.com/embed/miQqyfO66uw",NULL),
("./posters/67.jpg","Ray","1","3","La vida de Ray Charles es una alternancia de triunfos y fracasos personales que se suceden a lo largo de una dilatada y galardonada carrera en el mundo del espectáculo. Pero estamos hablando de un hombre que sintetizó sus luchas, su dolor y su oscuridad personal con la misma efectividad con la que supo fundir en su arte una miríada de estilos musicales: el jazz, el rhythm & blues, el rock & roll, el gospel y el country. Su historia tiene entonces un sentido muy distinto: la cadena de logros se transforma en el vibrante y conmovedor trayecto de un genio único con una visión propia que enseñó al mundo a escuchar música de una forma nueva. RAY es la biografía, nunca contada antes, de esa leyenda de la música americana que es Ray Charles. Se centra en el período más explosivo de la carrera de Charles, que comienza cuando este joven negro ciego se sube solo a un autobús en Florida y cruza el país para refinar su arte en la floreciente escena jazzística de Seattle.",NULL,"https://www.youtube.com/embed/jVHCQfcugdw","152 minutos"),
("./posters/68.jpg","Black Mirror","2","1","Black Mirror es una serie de televisión británica creada por Charlie Brooker que muestra el lado oscuro de la vida y la tecnología. La serie es producida por Zeppotron para Endemol. En cuanto al contenido del programa y la estructura, Brooker ha señalado que 'cada episodio tiene un tono diferente, un entorno diferente, incluso una realidad diferente, pero todos son acerca de la forma en que vivimos ahora - y la forma en que podríamos estar viviendo en 10 minutos si somos torpes'.","5","https://www.youtube.com/embed/jVHCQfcugdw",NULL),
("./posters/69.jpg","Detrás de sus ojos","2","2","Una madre soltera se adentra en un mundo de retorcidos juegos psicológicos cuando inicia una relación cuasi-no consentida con su jefe, un psiquiatra, y se hace amiga en secreto de su misteriosa esposa. La trama se bassa en un thriller sobre un triángulo amoroso perverso, más la introducción sutilmente de un elemento clave, que dará un giro notable a la obra.","1","https://www.youtube.com/embed/c4LtoWQaLxk",NULL),
("./posters/70.jpg","Her","1","1","En un futuro cercano, Theodore, un hombre solitario a punto de divorciarse que trabaja en una empresa como escritor de cartas para terceras personas, compra un día un nuevo sistema operativo basado en el modelo de Inteligencia Artificial, diseñado para satisfacer todas las necesidades del usuario. Para su sorpresa, se crea una relación romántica entre él y Samantha, la voz femenina de ese sistema operativo.",NULL,"https://www.youtube.com/embed/UVMcpZ42BkA","126 minutos"),
("./posters/71.jpg","Misión Imposible","1","9","Ethan Hunt es un superespía capaz de resolver cualquier arriesgada situación con la máxima elegancia. Forma parte de un competente equipo dirigido por el agente Jim Phelps, que ha vuelto a reunir a sus hombres para participar en una dificilísima misión: evitar la venta de un disco robado que contiene información secreta de vital importancia.",NULL,"https://www.youtube.com/embed/Ohws8y572KE","110 minutos"),
("./posters/72.jpg","El agente de C.I.P.O.L.","1","9","Guerra fría, años 60. Narra las aventuras de dos agentes secretos que se parecen más de lo que creen: Napoleon Solo, de la CIA, e Illya Kuryakin, del KGB. Ambos se ven obligados a olvidar sus diferencias y formar un equipo cuya misión será poner fin a una misteriosa organización criminal internacional que pretende desestabilizar el frágil equilibrio de poder provocado por la proliferación de las armas nucleares. La hija de un científico alemán desaparecido es la clave para infiltrarse en la organización, encontrar al científico y evitar una catástrofe mundial.",NULL,"https://www.youtube.com/embed/AeUzNxHHryQ","116 minutos"),
("./posters/73.jpg","Jumanji - Bienvenidos a la jungla","1","10","Cuatro adolescentes son absorbidos por un videojuego, en el que se convierten en avatares de personajes arquetípicos. Allí vivirán múltiples aventuras, al tiempo que buscan cómo salir de allí para volver a su mundo.",NULL,"https://www.youtube.com/embed/2QKg5SZ_35I","119 minutos"),
("./posters/21.jpg","Jumanji - The next level","1","10","Las aventuras continúan en el fantástico mundo del video juego Jumanji, donde nada es lo que parece. En esta ocasión, los jugadores vuelven al juego, pero sus personajes se han intercambiado entre sí, lo que ofrece un curioso plantel: los mismos héroes con distinta apariencia y habilidades. Pero, ¿dónde está el resto de la gente?",NULL,"https://www.youtube.com/embed/rBxcF-r9Ibs","97 minutos"),
("./posters/74.jpg","Mujer Maravilla 1984","1","10","En 1984, en plena guerra fría, Diana Prince, conocida como La Mujer Maravilla, se enfrenta al empresario Maxwell Lord y a su antigua amiga Barbara Minerva / Cheetah, una villana que posee fuerza y agilidad sobrehumanas.",NULL,"https://www.youtube.com/embed/sfM7_JLk-84","151 minutos"),
("./posters/75.jpg","El Contador","1","8","Christian Wolff es un contable y genio matemático, un hombre obsesivo con el orden y con mucha más afinidad con los números que con las personas, que lleva una doble vida como asesino despiadado.",NULL,"https://www.youtube.com/embed/DBfsgcswlYQ","128 minutos"),
("./posters/76.jpg","Mala Educación","1","3","Frank Tassone, uno de los superintendentes más destacados del distrito escolar de Roslyn en Nueva York se desvive a diario para que la educación de sus alumnos sea la mejor. Pero de forma paralela, este se lucra con dinero público para llevar una vida llena de lujos. Así, Tassone y su personal, amigos y familiares, se convierten en los principales sospechosos del mayor escándalo de malversación de fondos ocurrido en una escuela pública de toda la historia de los Estados Unidos. (Algunas personas aprenden de manera difícil.)",NULL,"https://www.youtube.com/embed/DBfsgcswlYQ","108 minutos"),
("./posters/78.jpg","Noche en el Museo","1","8","Un padre divorciado trata de establecerse, impresionar a su hijo y encontrar su destino. Él se presenta para un trabajo como vigilante nocturno en el Museo Americano de Historia Natural de la ciudad de Nueva York y, posteriormente, descubre que los objetos expuestos, animados por un artefacto mágico de Egipto, vuelven a la vida durante la noche. Al principio le va muy mal tratando de mantener el orden y la calma en el museo, pero al final se vuelve muy buen amigo de todos y juntos ayudan a recuperar aquel artefacto mágico egipcio, ya que ha sido robado por los antiguos vigilantes del museo.",NULL,"https://www.youtube.com/embed/B2G-8raHvOU","108 minutos"),
("./posters/79.jpg","Bohemian Rhapsody","1","3","Bohemian Rhapsody es una rotunda y sonora celebración de Queen, de su música y de su extraordinario cantante Freddie Mercury, que desafió estereotipos e hizo añicos tradiciones para convertirse en uno de los showmans más queridos del mundo. La película plasma el meteórico ascenso al olimpo de la música de la banda a través de sus icónicas canciones y su revolucionario sonido, su crisis cuando el estilo de vida de Mercury estuvo fuera de control, y su triunfal reunión en la víspera del Live Aid, en la que Mercury, mientras sufría una enfermedad que amenazaba su vida, lidera a la banda en uno de los conciertos de rock más grandes de la historia. Veremos cómo se cimentó el legado de una banda que siempre se pareció más a una familia, y que continúa inspirando a propios y extraños, soñadores y amantes de la música hasta nuestros días.",NULL,"https://www.youtube.com/embed/mP0VHJYFOAU","134 minutos"),
("./posters/80.jpg","Rock of ages","1","5","Los Ángeles, 1987: Un aspirante a roquero y una chica que trabajan en el mismo club (Bourbone Room) se enamoran y tratan de impedir que el local caiga en manos de unos empresarios que quieren demolerlo. Esta película es la adaptación cinematográfica del musical homónimo de Broadway.",NULL,"https://www.youtube.com/embed/mP0VHJYFOAU","123 minutos"),
("./posters/81.jpg","Super 8","1","1","Año 1979, en un pequeño pueblo de Ohio. Joe Lamb (Joel Courtney) es un muchacho que ha perdido a su madre en un accidente y que vive con su padre policía (Kyle Chandler). Comenzado el verano, y mientras rueda una película de zombis en Super 8 con sus amigos -y sobre todo con la bella Alice Dainard (Elle Fanning)-, Joe observa cómo una camioneta se estrella contra un tren de mercancías, provocando su descarrilamiento y un terrible accidente. A partir de ese momento cosas extrañas e inexplicables comienzan a suceder en el pueblo.",NULL,"https://www.youtube.com/embed/QtZ6BQRDk4g","82 minutos"),
("./posters/82.jpg","Jurassic World - El reino caido","1","8","Tras cuatro años de abandono del complejo turístico Jurassic World, la isla Nublar solo está habitada por los dinosaurios supervivientes, pero el volcán inactivo de la isla comienza a cobrar vida, Owen y Claire montan una campaña para rescatar a los dinosaurios restantes en la isla.",NULL,"https://www.youtube.com/embed/vn9mMeWcgoM","82 minutos"),
("./posters/83.jpg","Indiana Jones - y el Reino de la Calavera de Cristal","1","8","Guerra Fría (1957). Indiana Jones (Harrison Ford) y su amigo Mac (Ray Winstone) acaban de escapar de las garras de unos agentes soviéticos en un remoto aeropuerto. El decano de la Universidad (Jim Broadbent) le confiesa a su amigo el profesor Jones que las últimas misiones de Indy han fracasado y que está a punto de ser despedido. Mientras tanto, Indiana conoce a Mutt (Shia LaBeouf), un joven rebelde que le propone un trato: si le ayuda a resolver un problema personal, él, a cambio, le facilitaría uno de los descubrimientos más espectaculares de la historia: la Calavera de Cristal de Akator, que se encuentra en un lugar remoto del Perú. Pero los agentes soviéticos, dirigidos por la fría y bella Irina Spalko (Cate Blanchett), tienen el mismo objetivo.",NULL,"https://www.youtube.com/embed/WAdJf4wTC5Y","127 minutos"),
("./posters/84.jpg","Los Goonies","1","6","Mikey, un muchacho de trece años, que junto con su hermano mayor y sus amigos se hacen llamar 'Los Goonies', decide subir a jugar al desván de su casa, donde su padre guarda antigüedades. Allí, el grupo encuentra el mapa de un tesoro y emprende un fabuloso viaje para validar la veracidad de dicho mapa, y encontrar ese tesoro tan preciado por estos amigos inseparables.",NULL,"https://www.youtube.com/embed/hJ2j4oWdQtU","114 minutos"),
("./posters/85.jpg","Cars","1","6","El aspirante a campeón de carreras Rayo McQueen está sobre la vía rápida al éxito, la fama y todo lo que él había soñado, hasta que por error toma un desvío inesperado en la polvorienta y solitaria Ruta 66. Su actitud arrogante se desvanece cuando llega a una pequeña comunidad olvidada que le enseña las cosas importantes de la vida que había olvidado.",NULL,"https://www.youtube.com/embed/SbXIj2T-_uk","114 minutos"),
("./posters/86.jpg","Los pingüinos de Madagascar","1","6","Los pingüinos llevan sus misiones en su hábitat en el Parque Central. Aparecen Julien, el rey de los lémures, y sus súbditos Maurice y Mort, sus nuevos vecinos, que constituyen la exhibición de lémures en el zoológico. Ahora los pingüinos deben mantener las cosas bajo control, a menudo a pesar de las payasadas de los lémures así como auxiliar en labores poco comunes o aventuras fuera de lo común. Skipper rara vez llama al Rey Julien por su nombre, dirigiéndose a él siempre como 'Cola anillada' (por ser un lemur de cola anillada).",NULL,"https://www.youtube.com/embed/SbXIj2T-_uk","101 minutos"),
("./posters/87.jpg","Cementerio de animales","1","7","Louis Creed, su esposa y sus dos niños se instalan en una vivienda próxima a una carretera con mucho tráfico. Cerca de la casa hay un sendero que lleva a un cementerio de animales y también a un antiguo cementerio indio",NULL,"",NULL),
("./posters/88.jpg","Poltergeist","1","7","Una familia americana de clase media se traslada a vivir e una nueva casa en un aparentemente idílico barrio, pero dentro de la casa comienzan a suceder cosas extrañas, fenómenos paranormales para los que no hay explicación posible.",NULL,"https://www.youtube.com/embed/9eZgEKjYJqA","114 minutos"),
("./posters/89.jpg","El código Da Vinci","1","8","El catedrático y afamado simbologista Robert Langdon se ve obligado a acudir una noche al Museo del Louvre, cuando el asesinato de un restaurador deja tras de sí un misterioso rastro de símbolos y pistas. Con la ayuda de la criptógrafa de la policía Sophie Neveu y poniendo en juego su propia vida, Langdon descubre que la obra de Leonardo Da Vinci esconde una serie de misterios que apuntan a una sociedad secreta encargada de custodiar un antiguo secreto que ha permanecido oculto durante dos mil años.",NULL,"https://www.youtube.com/embed/lfqHb6INj3w","249 minutos"),
("./posters/90.jpg","Johnny English","1","5","Las joyas de la Corona de su Majestad han desaparecido. Detrás de ello se esconde Pascal Sauvage (John Malkovich), que también conspira para hacerse con el trono de la reina. La misión es asignada a Johnny English (Rowan Atkinson), un agente tan entregado al trabajo como inexperto. Desde ese momento la información confidencial, los coches de lujo y la tecnología más sofisticada forman parte de su rutina diaria. Johnny English aún no se lo acaba de creer. Quizás todo esto le venga algo grande, pero su empeño con la misión y dedicación para llegar hasta el final es incuestionable, especialmente después de conocer a la agente doble Lorna Campbell (Natalie Imbruglia). Parece ser que lo de estar enamorado aún hará más emocionante esto de salvar al país.",NULL,"https://www.youtube.com/embed/EG0MR5dFz7E","188 minutos"),
("./posters/91.jpg","Almost Famous","1","2","Homenaje al rock de los 70. Gracias a sus buenas críticas musicales, un adolescente que aspira a ser periodista es contratado por la revista 'Rolling Stone' para cubrir la gira de una famosa banda. A pesar de su juventud y de la oposición de su madre, el chico vivirá con los músicos y sus fans una aventura inolvidable. Basada en la propia experiencia de Crowe.",NULL,"https://www.youtube.com/embed/aQXh_AaJXaM","122 minutos"),
("./posters/92.jpg","Escuela de Rock","1","5","Dewey Finn -Jack Black- es un guitarrista con delirios de grandeza que es expulsado de su banda. Desesperado por encontrar un trabajo ante su falta de dinero, suplanta la identidad de un profesor sustituto para dar clase en una escuela privada a los pequeños alumnos pre-adolescentes de 5o grado a los que intentará enseñarles el 'rock & roll de alto voltaje'. Además entre sus alumnos está Yuki, un guitarrista prodigio de 9 años que puede ayudar a Dewey a ganar la competición de bandas de música... y de paso solucionar sus problemas económicos.",NULL,"https://www.youtube.com/embed/TExoc0MG4I4","110 minutos"),
("./posters/93.jpg","Mi pobre angelito","1","6","Kevin McAllister es un niño de ocho años, miembro de una familia numerosa, que accidentalmente se queda abandonado en su casa cuando toda la familia se marcha a pasar las vacaciones a Francia. Kevin aprende a valerse por sí mismo e incluso a protegerse de Harry y Marv, dos bribones que se proponen asaltar todas las casas cerradas de su vecindario. Cuando su madre Kate lo hecha en falta, realiza un pintoresco viaje de vuelta contra reloj a Chicago para recuperar a su hijo.",NULL,"https://www.youtube.com/embed/jEDaVHmw7r4","102 minutos"),
("./posters/94.jpg","Aprendices fuera de línea","1","5","Cuando dos cuarentones vendedores de relojes son despedidos de sus respectivos trabajos, convencidos ambos de que no se han adaptado a los cambios de las nuevas tecnologías, deciden empezar de nuevo y buscar trabajo en la empresa más exitosa de Internet: Google. Finalmente consiguen un contrato de prácticas como becarios. La locura comienza cuando se ven compitiendo para conseguir el puesto con jóvenes veinteañeros, mucho más listos y más familiarizados con el mundo digital que ellos.",NULL,"https://www.youtube.com/embed/tn02SPT6ivM","125 minutos"),
("./posters/95.jpg","Outsourced","2","5","Ambientada en el continente estadounidense, una empresa norteamericana que busca reducir los gastos, asciende a su mejor empleado del Call Center, poniéndolo a cargo del mismo. La única condición para dicho empleado, es viajar a la India, lugar en el mundo donde tercerizan el servicio ode atención al cliente, para abaratar costos. Allí, en la Ciudad de Bombay, los nativos le explican la cultura indú a los nóveles norteamericanos, y viceversa. Tendrán que convivir cada uno de los empleados de estos diferentes países, con sus pares y/o jefes opuestos en cultura.","1","https://www.youtube.com/embed/_wR3LhFlgGo",NULL),
("./posters/96.jpg","Miedo Profundo","1","4","Nancy, una estudiante de medicina apasionada del surfing, es una joven que trata de superar la pérdida de su madre. Un día, practicando surf en una solitaria playa mexicana se queda atrapada en un islote a sólo cien metros de la costa. El problema está en que un enorme tiburón blanco se interpone entre ella y la otra orilla.",NULL,"https://www.youtube.com/embed/EgdxIlSuB70","86 minutos"),
("./posters/97.jpg","Everest","1","3","Inspirada en los hechos que tuvieron lugar durante un intento por alcanzar el pico más alto del mundo, narra las peripecias de dos expediciones que se enfrentan a la peor tormenta de nieve conocida. En un desesperado esfuerzo por sobrevivir, el temple de los alpinistas se ve puesto a prueba al tener que enfrentarse a la furia desatada de los elementos y a obstáculos casi insuperables.",NULL,"https://www.youtube.com/embed/5ZQVpPiOji0","121 minutos"),
("./posters/98.jpg","La Familia Addams","1","6","El delirante y gótico estilo de vida de la peculiar familia Addams se ve amenazado peligrosamente cuando el codicioso dúo que forman madre e hijo, con la ayuda de un abogado sin ningún escrúpulos, conspiran para hacerse con la fortuna familiar... (No se pierdan las locutras de Gomez, Morticia, Tío Lucas, Merlina, El tío Cosas, Dedos y Largo)",NULL,"https://www.youtube.com/embed/G388UMkJIBE","101 minutos");


-- Tabla contenido_actores

INSERT INTO contenido_actores (contenidoID, actorID) VALUES
(1, 23),
(1, 24),
(1, 26),
(1, 516),
(1, 27),
(1, 28),
(2, 17),
(2, 18),
(2, 19),
(2, 20),
(2, 21),
(2, 22),
(3, 1),
(3, 2),
(3, 25),
(3, 3),
(3, 4),
(3, 5),
(4, 6),
(4, 7),
(4, 8),
(4, 9),
(4, 10),
(4, 11),
(5, 12),
(5, 13),
(5, 14),
(5, 15),
(5, 547),
(5, 16),
(6, 29),
(6, 30),
(6, 31),
(6, 28),
(6, 32),
(6, 33),
(7, 575),
(7, 34),
(7, 35),
(7, 36),
(7, 819),
(7, 37),
(8, 38),
(8, 39),
(8, 40),
(8, 41),
(8, 159),
(8, 42),
(9, 43),
(9, 44),
(9, 45),
(9, 46),
(9, 47),
(9, 48),
(10, 49),
(10, 50),
(10, 51),
(10, 52),
(10, 53),
(10, 54),
(11, 55),
(11, 56),
(11, 57),
(11, 58),
(11, 59),
(11, 60),
(11, 61),
(12, 62),
(12, 63),
(12, 64),
(12, 65),
(12, 66),
(12, 67),
(13, 68),
(13, 69),
(13, 70),
(13, 71),
(13, 72),
(13, 73),
(14, 74),
(14, 75),
(14, 76),
(14, 77),
(14, 78),
(14, 79),
(15, 80),
(15, 81),
(15, 825),
(15, 82),
(15, 83),
(15, 84),
(16, 85),
(16, 86),
(16, 87),
(16, 88),
(16, 361),
(16, 89),
(16, 90),
(16, 91),
(16, 92),
(16, 93),
(16, 94),
(16, 95),
(16, 96),
(16, 97),
(16, 98),
(16, 99),
(16, 559),
(16, 100),
(16, 466),
(16, 101),
(16, 102),
(16, 103),
(17, 104),
(17, 105),
(17, 106),
(17, 391),
(17, 107),
(17, 108),
(18, 164),
(18, 755),
(18, 109),
(18, 110),
(18, 111),
(18, 112),
(19, 113),
(19, 114),
(19, 115),
(19, 116),
(19, 117),
(19, 118),
(20, 119),
(20, 120),
(20, 121),
(20, 122),
(20, 123),
(20, 690),
(22, 124),
(22, 125),
(22, 126),
(22, 127),
(22, 128),
(22, 129),
(23, 130),
(23, 164),
(23, 131),
(23, 132),
(23, 133),
(23, 134),
(24, 135),
(24, 136),
(24, 138),
(24, 139),
(24, 140),
(25, 141),
(25, 163),
(25, 142),
(25, 364),
(25, 143),
(25, 620),
(26, 144),
(26, 145),
(26, 146),
(26, 147),
(27, 148),
(27, 149),
(27, 150),
(27, 151),
(27, 152),
(27, 153),
(28, 154),
(28, 163),
(28, 370),
(28, 155),
(28, 156),
(28, 157),
(28, 158),
(29, 159),
(29, 160),
(29, 267),
(29, 161),
(29, 162),
(29, 465),
(29, 701),
(30, 163),
(30, 164),
(30, 165),
(30, 166),
(30, 167),
(30, 168),
(30, 169),
(31, 170),
(31, 171),
(31, 172),
(31, 173),
(31, 174),
(31, 175),
(31, 176),
(32, 177),
(32, 178),
(32, 179),
(32, 181),
(32, 182),
(32, 183),
(33, 184),
(33, 185),
(33, 186),
(33, 187),
(33, 188),
(33, 189),
(33, 190),
(34, 191),
(34, 192),
(34, 193),
(34, 194),
(34, 195),
(34, 196),
(35, 197),
(35, 198),
(35, 199),
(35, 200),
(35, 201),
(35, 202),
(36, 203),
(36, 204),
(36, 205),
(36, 206),
(36, 207),
(36, 208),
(36, 209),
(37, 210),
(37, 211),
(37, 212),
(37, 213),
(37, 214),
(37, 215),
(37, 216),
(37, 217),
(38, 218),
(38, 219),
(38, 220),
(38, 221),
(38, 222),
(38, 223),
(38, 224),
(38, 225),
(38, 226),
(39, 227),
(39, 228),
(39, 229),
(39, 230),
(39, 231),
(39, 232),
(39, 233),
(39, 234),
(40, 235),
(40, 236),
(40, 237),
(40, 238),
(41, 239),
(41, 30),
(41, 240),
(41, 241),
(41, 242),
(41, 243),
(41, 244),
(41, 245),
(41, 246),
(42, 247),
(42, 248),
(42, 249),
(42, 250),
(42, 251),
(42, 252),
(42, 253),
(42, 254),
(42, 255),
(42, 256),
(43, 257),
(43, 258),
(43, 259),
(43, 260),
(43, 261),
(43, 262),
(43, 263),
(43, 264),
(43, 265),
(44, 266),
(44, 267),
(44, 268),
(44, 29),
(44, 269),
(44, 270),
(44, 271),
(44, 272),
(44, 273),
(44, 274),
(45, 275),
(45, 276),
(45, 361),
(45, 277),
(45, 278),
(45, 279),
(45, 280),
(45, 281),
(49, 282),
(49, 283),
(49, 284),
(49, 268),
(49, 285),
(49, 286),
(49, 287),
(49, 130),
(49, 288),
(46, 289),
(46, 290),
(46, 291),
(46, 292),
(46, 361),
(46, 293),
(46, 294),
(46, 295),
(46, 296),
(47, 297),
(47, 298),
(47, 299),
(47, 300),
(47, 301),
(47, 302),
(47, 303),
(47, 304),
(47, 305),
(48, 306),
(48, 307),
(48, 308),
(48, 309),
(48, 310),
(48, 311),
(48, 312),
(48, 314),
(50, 315),
(50, 316),
(50, 317),
(50, 318),
(50, 319),
(50, 320),
(50, 321),
(50, 322),
(50, 323),
(50, 324),
(51, 325),
(51, 326),
(51, 327),
(51, 328),
(51, 329),
(51, 330),
(51, 331),
(51, 332),
(51, 333),
(52, 334),
(52, 335),
(52, 336),
(52, 825),
(52, 337),
(52, 338),
(52, 339),
(52, 340),
(52, 341),
(53, 342),
(53, 343),
(53, 344),
(53, 345),
(53, 346),
(53, 347),
(53, 348),
(53, 349),
(53, 350),
(54, 351),
(54, 352),
(54, 353),
(54, 354),
(54, 355),
(54, 55),
(54, 356),
(54, 357),
(54, 358),
(55, 359),
(55, 360),
(55, 361),
(55, 362),
(55, 363),
(55, 364),
(55, 365),
(55, 366),
(55, 367),
(56, 368),
(56, 178),
(56, 369),
(56, 370),
(56, 371),
(56, 372),
(56, 373),
(56, 374),
(56, 375),
(57, 376),
(57, 377),
(57, 378),
(57, 379),
(57, 380),
(57, 381),
(57, 382),
(57, 383),
(57, 384),
(58, 239),
(58, 385),
(58, 386),
(58, 387),
(58, 388),
(58, 389),
(58, 383),
(58, 105),
(58, 390),
(58, 391),
(59, 392),
(59, 393),
(59, 394),
(59, 395),
(59, 396),
(59, 397),
(59, 398),
(59, 399),
(59, 400),
(59, 401),
(59, 402),
(59, 403),
(59, 377),
(59, 404),
(59, 405),
(59, 406),
(59, 407),
(59, 408),
(59, 409),
(60, 393),
(60, 410),
(60, 411),
(60, 412),
(60, 413),
(60, 414),
(60, 415),
(60, 416),
(60, 417),
(60, 418),
(60, 419),
(60, 420),
(60, 421),
(60, 422),
(60, 423),
(60, 424),
(60, 425),
(60, 392),
(60, 426),
(61, 427),
(61, 428),
(61, 429),
(61, 430),
(61, 431),
(61, 432),
(61, 433),
(62, 434),
(62, 435),
(62, 436),
(62, 12),
(62, 437),
(62, 438),
(62, 174),
(62, 439),
(62, 440),
(63, 442),
(63, 440),
(63, 443),
(63, 444),
(63, 445),
(63, 446),
(63, 447),
(63, 448),
(64, 440),
(64, 449),
(64, 450),
(64, 451),
(64, 452),
(64, 453),
(64, 454),
(64, 455),
(64, 456),
(64, 457),
(64, 458),
(64, 459),
(64, 460),
(64, 461),
(64, 462),
(64, 463),
(64, 464),
(64, 465),
(65, 466),
(65, 467),
(65, 468),
(65, 469),
(65, 470),
(65, 471),
(65, 472),
(65, 473),
(65, 474),
(65, 475),
(65, 476),
(65, 477),
(65, 478),
(66, 156),
(66, 479),
(66, 480),
(66, 481),
(66, 482),
(66, 483),
(66, 484),
(66, 485),
(66, 486),
(66, 396),
(66, 199),
(66, 487),
(66, 488),
(66, 489),
(66, 490),
(67, 491),
(67, 492),
(67, 493),
(67, 494),
(67, 495),
(67, 496),
(67, 497),
(67, 498),
(67, 499),
(68, 500),
(68, 501),
(68, 502),
(68, 503),
(68, 504),
(68, 505),
(68, 506),
(68, 507),
(68, 508),
(68, 509),
(68, 510),
(68, 511),
(68, 512),
(68, 513),
(68, 514),
(68, 515),
(68, 516),
(68, 517),
(68, 518),
(68, 519),
(68, 520),
(68, 521),
(68, 522),
(68, 523),
(68, 524),
(68, 525),
(68, 526),
(68, 527),
(68, 528),
(68, 529),
(68, 530),
(68, 531),
(68, 532),
(68, 533),
(68, 534),
(68, 535),
(68, 536),
(68, 537),
(68, 538),
(68, 539),
(68, 540),
(68, 541),
(68, 542),
(68, 543),
(68, 544),
(68, 545),
(68, 546),
(68, 547),
(68, 549),
(68, 550),
(68, 551),
(68, 552),
(68, 339),
(68, 553),
(68, 554),
(68, 555),
(68, 556),
(68, 557),
(68, 558),
(68, 559),
(68, 466),
(68, 560),
(68, 561),
(68, 562),
(68, 563),
(68, 564),
(68, 177),
(68, 106),
(68, 565),
(69, 566),
(69, 567),
(69, 568),
(69, 569),
(69, 570),
(69, 571),
(69, 572),
(69, 573),
(69, 574),
(70, 575),
(70, 159),
(70, 244),
(70, 223),
(70, 576),
(70, 178),
(70, 577),
(70, 578),
(70, 579),
(71, 580),
(71, 581),
(71, 582),
(71, 583),
(71, 584),
(71, 585),
(71, 586),
(71, 587),
(71, 588),
(72, 30),
(72, 589),
(72, 590),
(72, 591),
(72, 592),
(72, 593),
(72, 80),
(72, 594),
(72, 595),
(72, 596),
(72, 597),
(73, 598),
(73, 599),
(73, 600),
(73, 601),
(73, 602),
(73, 603),
(73, 604),
(73, 605),
(73, 607),
(73, 608),
(73, 609),
(73, 610),
(73, 252),
(73, 611),
(21, 598),
(21, 599),
(21, 600),
(21, 601),
(21, 612),
(21, 602),
(21, 603),
(21, 604),
(21, 605),
(21, 607),
(21, 608),
(21, 609),
(21, 610),
(21, 252),
(21, 611),
(21, 613),
(21, 614),
(74, 240),
(74, 615),
(74, 165),
(74, 1),
(74, 616),
(74, 246),
(74, 617),
(74, 618),
(74, 619),
(75, 239),
(75, 235),
(75, 208),
(75, 620),
(75, 621),
(75, 622),
(75, 623),
(75, 480),
(75, 624),
(75, 625),
(75, 626),
(75, 627),
(75, 628),
(75, 629),
(75, 630),
(75, 631),
(75, 632),
(75, 633),
(76, 634),
(76, 635),
(76, 636),
(76, 605),
(76, 637),
(76, 638),
(76, 639),
(76, 640),
(76, 641),
(76, 642),
(76, 643),
(76, 644),
(76, 645),
(76, 646),
(78, 647),
(78, 648),
(78, 649),
(78, 650),
(78, 651),
(78, 652),
(78, 653),
(78, 654),
(78, 655),
(78, 656),
(78, 657),
(78, 471),
(78, 658),
(79, 471),
(79, 659),
(79, 660),
(79, 661),
(79, 662),
(79, 663),
(79, 346),
(79, 664),
(79, 665),
(80, 666),
(80, 667),
(80, 580),
(80, 668),
(80, 669),
(80, 670),
(80, 671),
(80, 385),
(80, 672),
(80, 673),
(80, 674),
(80, 675),
(80, 676),
(80, 677),
(80, 678),
(81, 679),
(81, 680),
(81, 681),
(81, 194),
(81, 682),
(81, 683),
(81, 684),
(81, 685),
(81, 686),
(82, 178),
(82, 177),
(82, 399),
(82, 687),
(82, 688),
(82, 689),
(82, 690),
(82, 691),
(82, 692),
(82, 693),
(82, 694),
(82, 695),
(82, 696),
(83, 697),
(83, 698),
(83, 699),
(83, 700),
(83, 701),
(83, 702),
(83, 703),
(83, 704),
(83, 705),
(84, 706),
(84, 707),
(84, 708),
(84, 709),
(84, 710),
(84, 711),
(84, 712),
(84, 713),
(84, 714),
(85, 655),
(85, 715),
(85, 716),
(85, 717),
(85, 718),
(85, 719),
(85, 720),
(85, 721),
(85, 722),
(86, 217),
(86, 723),
(86, 724),
(86, 725),
(86, 726),
(86, 727),
(87, 728),
(87, 729),
(87, 730),
(87, 731),
(87, 732),
(87, 733),
(87, 734),
(87, 735),
(87, 736),
(88, 737),
(88, 738),
(88, 739),
(88, 740),
(88, 741),
(88, 743),
(88, 744),
(88, 745),
(89, 289),
(89, 746),
(89, 747),
(89, 584),
(89, 362),
(89, 748),
(89, 749),
(89, 750),
(89, 751),
(90, 752),
(90, 753),
(90, 754),
(90, 755),
(90, 756),
(90, 757),
(90, 758),
(90, 759),
(90, 760),
(91, 411),
(91, 761),
(91, 762),
(91, 196),
(91, 763),
(91, 764),
(91, 765),
(91, 766),
(91, 767),
(92, 600),
(92, 768),
(92, 769),
(92, 770),
(92, 771),
(92, 772),
(92, 773),
(92, 774),
(92, 124),
(93, 775),
(93, 776),
(93, 777),
(93, 778),
(93, 780),
(93, 781),
(93, 782),
(93, 783),
(94, 655),
(94, 784),
(94, 785),
(94, 786),
(94, 787),
(94, 222),
(94, 788),
(94, 790),
(94, 791),
(94, 205),
(94, 792),
(94, 793),
(94, 794),
(94, 795),
(94, 796),
(94, 797),
(94, 319),
(94, 798),
(94, 799),
(95, 800),
(95, 801),
(95, 802),
(95, 803),
(95, 804),
(95, 805),
(95, 806),
(95, 807),
(95, 808),
(95, 809),
(95, 810),
(95, 811),
(95, 812),
(96, 813),
(96, 814),
(96, 815),
(96, 816),
(96, 817),
(96, 818),
(96, 819),
(96, 820),
(96, 821),
(97, 193),
(97, 707),
(97, 822),
(97, 823),
(97, 824),
(97, 825),
(97, 826),
(97, 542),
(97, 343),
(97, 616),
(97, 827),
(97, 828),
(97, 829),
(97, 590),
(97, 455),
(97, 830),
(98, 831),
(98, 832),
(98, 833),
(98, 834),
(98, 835),
(98, 836),
(98, 837),
(98, 838),
(98, 839);








